version: '3.9'
services:
  monitoring:
    image: nicolargo/glances:latest-full
    restart: unless-stopped
    pid: host
    privileged: true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /opt/containers/glances/run/user/1000/podman/podman.sock:/run/user/1000/podman/podman.sock:ro
      - /opt/containers/glances/glances.conf:/etc/glances.conf
    environment:
      - GLANCES_OPT= -w
      - TZ=Europe/Paris
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.glances.entrypoints=http
      - traefik.http.routers.glances.rule=Host(`your-website`)
      - traefik.http.middlewares.glances-https-redirect.redirectscheme.scheme=https
      - traefik.http.middlewares.glances-auth.basicauth.users=guillaume:your-password
      - traefik.http.routers.glances.middlewares=glances-https-redirect
      - traefik.http.routers.glances-secure.entrypoints=https
      - traefik.http.routers.glances-secure.rule=Host(`your-website`)
      - traefik.http.routers.glances-secure.middlewares=glances-auth
      - traefik.http.routers.glances-secure.tls=true
      - traefik.http.routers.glances-secure.tls.certresolver=http
      - traefik.http.routers.glances-secure.service=glances
      - traefik.http.services.glances.loadbalancer.server.port=61208
networks:
  proxy:
    external: true
